# Generated by Django 3.2.1 on 2021-05-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('release_Date', models.DateField()),
                ('directed_by', models.CharField(max_length=50)),
                ('series_name', models.CharField(max_length=50)),
            ],
        ),
    ]
